<script type="text/javascript" src='<?php echo Mage::getBaseUrl('js') ?>bbva.js'></script>


<form method="post" name="Bbva" id="bbva_standard_checkout" action="<?php echo $action ?>" target="bbva_window">


<input type="hidden" value="<?php echo $peticion;?>" name="peticion" id="peticion"/>
<input type="hidden" value="<?php echo $windowstate ?>" name="windowstate" id="windowstate"/>

</form>


<center><br /><br />

<h3><?php echo $this->__('Clicking the button will be redirected to  TPV Bbva to make your payment securely.') ?></h3><br />
<img src='<?php echo $this->getSkinUrl('images/bbva/bbva_tpv.jpg') ?>' border="0" /><br/>
<input class="form-button" type="button" onclick="javascript:openBbvaWindow();" value='<?php echo $this->__('Go to Bbva') ?>' />
</center>